#ifndef CONFIG_TEMPLATE_H__
#define CONFIG_TEMPLATE_H__

const char* fmtHeader =
"/*                                                         \n"
" * $Id: ConfigTemplate.h 93 2011-01-29 12:48:42Z vintage $                                                    \n"
" */                                                        \n"
"#ifndef AUTO_CONFIG_H__                                     \n"
"#define AUTO_CONFIG_H__                                     \n"
"#include <lwpr.h>                                          \n"
"#include <string>                                          \n"
"#include <assert.h>                                        \n"
"#include <limits.h>                                        \n"
"                                                           \n"
"using std::string;                                         \n"
"                                                           \n"
"class AutoConfig : public LWPR::ConfigProperty              \n"
"{                                                          \n"
"public:                                                    \n"
"%s                                                         \n"
"public:                                                    \n"
"	AutoConfig();                                            \n"
"	virtual ~AutoConfig();                                   \n"
"	static AutoConfig* GetInstance();                        \n"
"	virtual void PrintConfig();                             \n"
"                                                           \n"
"public:                                                    \n"
"%s                                                         \n"
"protected:                                                 \n"
"	virtual void DoPropConstruct();                         \n"
"                                                           \n"
"private:                                                   \n"
"%s                                                         \n"
"};                                                         \n"
"                                                           \n"
"#define CONFIG() AutoConfig::GetInstance()                  \n"
"                                                           \n"
"#endif // end of APP_CONFIG_H__                            \n"
;

const char* fmtCpp =
"/*                                                         \n"
" * $Id: ConfigTemplate.h 93 2011-01-29 12:48:42Z vintage $                                                    \n"
" */                                                        \n"
"#include \"AutoConfig.h\"                                   \n"
"                                                           \n"
"AutoConfig::AutoConfig()                                     \n"
"{                                                          \n"
"%s                                                         \n"
"}                                                          \n"
"                                                           \n"
"AutoConfig::~AutoConfig()                                    \n"
"{                                                          \n"
"}                                                          \n"
"                                                           \n"
"AutoConfig* AutoConfig::GetInstance()                        \n"
"{                                                          \n"
"	static AutoConfig *singleton = new AutoConfig();          \n"
"	return singleton;                                       \n"
"}                                                          \n"
"                                                           \n"
"void AutoConfig::PrintConfig()                              \n"
"{                                                          \n"
"%s                                                         \n"
"}                                                          \n"
"                                                           \n"
"void AutoConfig::DoPropConstruct()                          \n"
"{                                                          \n"
"%s                                                         \n"
"}                                                          \n"
;
#endif
