#ifndef TUX_MAIN_STUB_H__
#define TUX_MAIN_STUB_H__
const char* g_fmtMainStub =
"#include <stdio.h>                                                   \n"
"#include <atmi.h>                                                    \n"
"                                                                     \n"
"#if defined(__cplusplus)                                             \n"
"extern \"C\" {                                                       \n"
"#endif                                                               \n"
"%s                                                                   \n"
"                                                                     \n"
"#if defined(__cplusplus)                                             \n"
"}                                                                    \n"
"#endif                                                               \n"
"                                                                     \n"
"static TMDSPTCHTBL_T _tmdsptchtbl[] = {                              \n"
"%s                                                                   \n"
"	{ NULL, NULL}                                                     \n"
"};                                                                   \n"
"                                                                     \n"
"#ifndef _TMDLLIMPORT                                                 \n"
"#define _TMDLLIMPORT                                                 \n"
"#endif                                                               \n"
"                                                                     \n"
"static TMSVRARGS_T tmsvrargs = {                                     \n"
"	&_tmdsptchtbl[0],                                                 \n"
"	sizeof(_tmdsptchtbl) / sizeof(TMDSPTCHTBL_T) - 1                  \n"
"};                                                                   \n"
"                                                                     \n"
"int                                                                  \n"
"#ifdef _TMPROTOTYPES                                                 \n"
"main(int argc, char **argv)                                          \n"
"#else                                                                \n"
"main(argc,argv)                                                      \n"
"int argc;                                                            \n"
"char **argv;                                                         \n"
"#endif                                                               \n"
"{                                                                    \n"
"#ifdef TMMAINEXIT                                                    \n"
"#include \"mainexit.h\"                                              \n"
"#endif                                                               \n"
"                                                                     \n"
"	return _tmstartserver(argc, argv, &tmsvrargs);                    \n"
"}                                                                    \n"
;
#endif // end of TUX_MAIN_STUB_H__
